# Compute yearly means of circulation variables

cdo yearmonmean ERA5_u_component_200hPa.nc ERA5_u_component_200hPa_yearmonmean.nc
cdo yearmonmean ERA5_total_cloud_cover.nc ERA5_total_cloud_cover_yearmonmean.nc
cdo yearmonmean ERA5_geopotential_500hPa.nc ERA5_geopotential_500hPa_yearmonmean.nc
